micronaut:
  application:
    name: micronautmongodbreactivehealthcheckfails
  server:
    netty:
      max-header-size: 20000
mongodb:
  uri: 'mongodb://localhost:57017/sacs'
  connection-pool:
    max-connection-idle-time: 'PT1M'
